name = "star-timeline"
main = "src/index.js"
compatibility_date = "2026-08-01"
assets = { directory = "./content" }

[[d1_databases]]
binding = "DB"
database_name = "star-timeline"
database_id = "a7be9729-3e90-4f81-8acd-6e2faa9eeafa"