name = "star-timeline-api"
main = "src/index.js"
compatibility_date = "2026-08-01"
assets = { directory = "./content" }

[[d1_databases]]
binding = "DB"
database_name = "star-timeline"
database_id = "<在创建后用 npx wrangler d1 info 查询并填入>"
